### ISSUE TITLE
How do I uninstall this this?

### ISSUE THREAD

**Issue by silocoder** [alex1701c/NordVPNKrunner#3]
Need to try something else. Thanks!

**Comment by alex1701c** [comment]
Go to the build directory and run:  
```bash
sudo make uninstall
kquitapp5 krunner;kstart5 krunner
```

**Comment by silocoder** [comment]
I also installed these:

sudo apt install cmake extra-cmake-modules build-essential libkf5runner-dev libkf5textwidgets-dev qtdeclarative5-dev gettext libkf5notifications-dev libkf5kcmutils-dev

Should I uninstall them?

**Comment by alex1701c** [comment]
If you don't need them otherwise you could free a bit of disk space.

But If you are not sure if you need them you can lust uninstall the -dev packages, that should be fine.
