### ISSUE TITLE
default server

### ISSUE THREAD

**Issue by JediBrooker** [alex1701c/NordVPNKrunner#4]
I changed the default server in krunner settings to SG but it still defaults to US. I tried restarting to see if that needed to happen to make it stick but no. Why do you think that is?

Surely the default server should be the closest/fastest server.

**Comment by alex1701c** [comment]
Setting the value works for me, weird..n

>Surely the default server should be the closest/fastest server.

Depends on your usecase, if you want to connect to a specific country to avoid content restrictions that might not always be the fastest.

But I have been thinking if it might be nice to display the recent servers/countries one has connected to and letting nordvpn choose it if no value is explicitly set.

**Comment by alex1701c** [comment]
@JediBrooker Any further thoughts? Otherwise I'd close this issue.
