### ISSUE TITLE
Errror compile in Archlinux

### ISSUE THREAD

**Issue by snock** [alex1701c/NordVPNKrunner#5]
**/home/nicolas/.cache/yay/plasma5-runners-nordvpn/src/NordVPNKrunner-2.1.0/src/config/nordvpn_config.cpp:14:10: error fatal: kcmutils_version.h: No existe el fichero o el directorio
   14 | #include "kcmutils_version.h"**
      |          ^~~~~~~~~~~~~~~~~~~~
compilación terminada.
make[2]: *** [src/CMakeFiles/kcm_krunner_nordvpn.dir/build.make:94: src/CMakeFiles/kcm_krunner_nordvpn.dir/config/nordvpn_config.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:553: src/CMakeFiles/kcm_krunner_nordvpn.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
/home/nicolas/.cache/yay/plasma5-runners-nordvpn/src/NordVPNKrunner-2.1.0/src/runner/nordvpn.cpp: En la función miembro ‘virtual void NordVPN::init()’:
/home/nicolas/.cache/yay/plasma5-runners-nordvpn/src/NordVPNKrunner-2.1.0/src/runner/nordvpn.cpp:13:13: aviso: ‘void Plasma::AbstractRunner::setSpeed(Plasma::AbstractRunner::Speed)’ es obsoleto: Since 5.81. the concept of delayed runners is deprecated, see method docs for porting instructions [-Wdeprecated-declarations]
   13 |     setSpeed(NormalSpeed);
      |     ~~~~~~~~^~~~~~~~~~~~~
En el fichero incluido desde /usr/include/KF5/KRunner/KRunner/AbstractRunner:1,
                 desde /home/nicolas/.cache/yay/plasma5-runners-nordvpn/src/NordVPNKrunner-2.1.0/src/runner/nordvpn.h:5,
                 desde /home/nicolas/.cache/yay/plasma5-runners-nordvpn/src/NordVPNKrunner-2.1.0/src/runner/nordvpn.cpp:1:
/usr/include/KF5/KRunner/krunner/abstractrunner.h:517:10: nota: se declara aquí
  517 |     void setSpeed(Speed newSpeed);
      |          ^~~~~~~~
[ 94%] Linking CXX shared module ../bin/krunner_nordvpn.so
[ 94%] Built target krunner_nordvpn
make: *** [Makefile:166: all] Error 2
==> ERROR: Se produjo un fallo en build().
    Cancelando...
 -> error compilando: plasma5-runners-nordvpn
┌─( nicolas ) » { ~/Descargas/NordVPNKrunner-2.1.0/build }

**Comment by alex1701c** [comment]
That is a fallout from a KDE Frameworks change. I will fix the issue and create a new release.

**Comment by alex1701c** [comment]
It was fixed in master for a while now. I created a Github release and updated the KDE Store file.
