### ISSUE TITLE
%STATUS not displaying

### ISSUE THREAD

**Issue by nlynzaad** [alex1701c/NordVPNKrunner#6]
Hi,

I'm having a strange issue as per the attached screenshot the %STATUS value does not appear in krunner. Not sure if this might be related to the recent update in frameworks or nordvpn or most probably just a bad setting or something on my end. I remember this working when I tried the plugin probably a year ago.

Running on Manjaro (Kernel: 5.18.6, KDE Plasma: 5.24.5, KDE frameworks: 5.95, QT: 5.15.5)
![image](https://user-images.githubusercontent.com/44094871/175769568-0809c877-4e07-4f78-b979-15d9db044edd.png)

**Comment by alex1701c** [comment]
>Not sure if this might be related to the recent update in frameworks 

I have KDE Frameworks master and did not experience any issues.

>or nordvpn or most probably just a bad setting or something on my end

What is your nordvpn version?

Could you compile the plugin with https://invent.kde.org/-/snippets/2252 applied and see what krunner prints out when you run `krunner --replace vpn` in a terminal?

**Comment by alex1701c** [comment]
@dragonhelios Please provide the requested information, otherwise I can not debug this further.

**Comment by nlynzaad** [comment]
Apologies for the delayed reply. Attached output.

I'm running nordvpn version 3.14.1

[debug.txt](https://github.com/alex1701c/NordVPNKrunner/files/9084132/debug.txt)

**Comment by alex1701c** [comment]
>I'm running nordvpn version 3.14.1

I have an older version. I will update and check if the issue is reproducible.

>Apologies for the delayed reply. Attached output.

The parsing of the NordVPN CLI output has issues. Thanks for posting the file!

**Comment by alex1701c** [comment]
I can not install any newer NordVPN version though apt :/.

Please check if https://github.com/alex1701c/NordVPNKrunner/tree/fix-new-version fixes the issue. It is just a good guess from my side ;)

**Comment by nlynzaad** [comment]
Thanks this seems to have resolved the issue.

**Comment by alex1701c** [comment]
I have created a new release on Github and will upload the tar to the KDE store too.
