### ISSUE TITLE
Plasma 6 support

### ISSUE THREAD

**Issue by Strit** [alex1701c/NordVPNKrunner#7]
I used this plugin for Plasma 5.

But I see there has been no release made for Plasma 6, so it currently does not work on my desktop.

Any chance for a release that has this supported soon?

**Comment by alex1701c** [comment]
You could try the master branch, there I have added Plasma6 support a while ago

**Comment by Strit** [comment]
Yeah. I was asking for a release with it, so that the AUR package could be updated/made for Plasma 6. :)

**Comment by alex1701c** [comment]
https://github.com/alex1701c/NordVPNKrunner/releases/tag/3.0.0

**Comment by Strit** [comment]
Awesome, thanks! :smiley:

**Comment by Strit** [comment]
CMake still looks for qt5 stuff. I get this error when trying to build version 3.0.0 on a clean system:

```
CMake Error at CMakeLists.txt:27 (find_package):
  Could not find a package configuration file provided by "Qt5" (requested
  version 5.15.0) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in build().
    Aborting...
```

So it still expects all the KF5 stuff, and will use that by default if found, so it does not build against QT6/KF6 yet.

**Comment by alex1701c** [comment]
You are right - I have pushed an adjustment to the install script. Please say if all works fine now  :)

**Comment by Strit** [comment]
Thanks.

That commits seems to fix it! :smiley:
