### ISSUE TITLE
Unable to compile NordVPNKrunner

### ISSUE THREAD

**Issue by IoSonoPiero** [alex1701c/NordVPNKrunner#8]
Hello,
I'm on Tuxedo OS (Kubuntu 22.04) and trying to install NordVPNKrunner, with KDE Plasma 6

I've already installed the following packages with the command you wrote on Readme:
`sudo apt install cmake extra-cmake-modules build-essential libkf5runner-dev libkf5textwidgets-dev qtdeclarative5-dev gettext libkf5notifications-dev libkf5kcmutils-dev`

But I get this error during compilation when I try to install NordVPNKrunner as an extension:
![Schermata_20240505_215142](https://github.com/alex1701c/NordVPNKrunner/assets/82404704/d697bee3-0ee2-4367-a17b-3963bbf99df5)

I have the same error if I try to compile from the repository with the following:
`curl https://raw.githubusercontent.com/alex1701c/NordVPNKrunner/master/install.sh | bash`

Can you help me, please?

**Comment by alex1701c** [comment]
Maybe you need the qt6-base-dev package. Depending on your distibution.

I agree the error message being weird, I will give it a look

**Comment by IoSonoPiero** [comment]
Hello, adding qt6-base-dev package, I get:
![Schermata_20240508_171147-1](https://github.com/alex1701c/NordVPNKrunner/assets/82404704/0e3d43ad-cdb9-4ae6-a5b5-41e1c4c957c2)

**Comment by alex1701c** [comment]
> I've already installed the following packages with the command you wrote on Readme:

I think the 5 versions may just be replaced with 6. I hope distos have not renamed their modules.

**Comment by alex1701c** [comment]
This should improve the error message: https://invent.kde.org/frameworks/extra-cmake-modules/-/merge_requests/442

**Comment by IoSonoPiero** [comment]
Thanks!

**Comment by alex1701c** [comment]
`sudo apt install cmake extra-cmake-modules build-essential libkf6runner-dev gettext libkf6notifications-dev libkf6kcmutils-dev`

Those should be enough - I had cleaned up a few dependencies

**Comment by IoSonoPiero** [comment]
So, using:

`sudo apt install cmake extra-cmake-modules build-essential libkf6runner-dev libkf6textwidgets-dev gettext libkf6kcmutils-dev libkf6notifications-dev`

I got these attached: messages and errors.
[errors.txt](https://github.com/alex1701c/NordVPNKrunner/files/15251058/errors.txt)
[messages.txt](https://github.com/alex1701c/NordVPNKrunner/files/15251060/messages.txt)

**Comment by IoSonoPiero** [comment]
> `sudo apt install cmake extra-cmake-modules build-essential libkf6runner-dev gettext libkf6notifications-dev libkf6kcmutils-dev`
> 
> Those should be enough - I had cleaned up a few dependencies

I was doing by my own, LOL, while you wrote that!

**Comment by alex1701c** [comment]
I will update the docs - as I need to do in the other repos ^^
